name: Create Changelog

on: [workflow_dispatch]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Install git core'
        run: |
          npm install @actions/core

      - name: 'Generate next build number'
        id: changelog
        uses: "./.github/actions/changelog"
